company:
  title: SuperMark
  tagline:
    en: UX/UI, development and marketing
    ru: UX/UI, разработка и маркетинг
  street: ''
  city:
    en: Herceg Novi
    ru: Херцег Нови
  postal_code: 85340
  country:
    en: Montenegro
    ru: Черногория
  phone: +382 69 184524
  email: vladimir.nikishin(at)gmail.com
  area_served: RU
  opening_hours: Mo, Tu, We, Th, Fr 10:00-18:00
  price_range: $20/h
  latitude: ''
  longitude: ''
  map: https://goo.gl/maps/3REM94L3zk7ahRCbA

# ------------------------------------------------------------------------------
# Settings
# ------------------------------------------------------------------------------

facebook_like: true

# ------------------------------------------------------------------------------
# Texts
# ------------------------------------------------------------------------------

headings:
  ydnad:
    en: '#You_Don_t_Need_a_Department'
    ru: '#ВамНеНуженОтдел'

descriptions:
  one_man_army:
    en: 'A person works for three. Get progressive web design, modern development standards, proven and latest promotion techniques three times cheaper. I’ve been in the business since 1999.'
    ru: 'Один универсал работает за троих. Прогрессивный веб-дизайн. Современные стандарты разработки. А также всегда проверенные и новейшие методики продвижения. В диджитал-маркетинге с 1999 года.'

labels:
  logo:
    en: 'SuperMark Logo'
    ru: Фирменный знак SuperMark'а
  search:
    en: 'Search'
    ru: 'Поиск'
  write:
    en: 'Write:'
    ru: 'Пишите:'

  buttons:
    back:
      en: 'Back'
      ru: 'Назад'
    cancel:
      en: 'Cancel'
      ru: 'Отмена'
    close:
      en: 'Close'
      ru: 'Закрыть'
    contact:
      en: 'Contact me'
      ru: 'Обращайтесь'
    help:
      en: 'Can I help you?'
      ru: 'Вам помочь?'
    next:
      en: 'Next'
      ru: 'Вперёд'
    previous:
      en: 'Previous'
      ru: 'Назад'
    share:
      en: 'Share'
      ru: 'Поделиться'

messages:
  js_disabled:
    en: 'JavaScript is currently disabled. The site requires JavaScript to function correctly. Please <a href="http://enable-javascript.com/" target="_blank" rel="noopener noreferrer nofollow">enable Javascript in your browser</a>.'
    ru: 'В вашем браузере выключен JavaScript. Поэтому не работает основная навигация, не открываются окна дополнительной информации. <a href="https://yandex.ru/support/mail/tech-glossary.html#js-enable" target="_blank" rel="noopener noreferrer nofollow">Включите Javascript</a>.'

disqus: smark
