- id: "subsection-development"
  active: false
  button:
    phone:
      en: "Des."
      ru: "Раз"
    base:
      en: "Development"
      ru: "Разработка"
  content:
    en:
      - "<strong>Websites</strong> on traditional and headless CMS or static site generators: WordPress, Strapi, Jekyll."
      - "<strong>Complex cross-browser responsive layouts</strong> built on HTML that meets W3C standards, including WCAG. Elegant, semantic markup extended with schema.org microdata. Templating engines: Nunjucks, Pug, Twig."
      - "<strong>Properly structured CSS</strong> using best practices and modules. CSS grid, Flexbox, custom properties, SVG sprites, custom Sass functions, etc."
      - "<strong>Vanilla JavaScript</strong> <code>(\"es2023\": true)</code>."
      - "<strong>Site speed optimization</strong> according to Lighthouse recommendations."
    ru:
      - "<strong>Сайты на генераторах</strong> или традиционных и headless CMS: WordPress, Strapi, Jekyll."
      - "<strong>Сложные кроссбраузерные адаптивные макеты</strong>, собранные на HTML, соответствующем стандартам W3C, включая WCAG. Элегантная, семантическая разметка, расширенная микроданными в формате schema.org. Шаблонизаторы: Nunjucks, Pug, Twig."
      - "<strong>Правильно структурированные CSS</strong> с применением передовых практик и модулей. CSS grid, Flexbox, custom properties, SVG-спрайты, пользовательские Sass-функции и т. д."
      - "<strong>«Ванильный» JavaScript</strong> <code>(\"es2023\": true)</code>."
      - "<strong>Оптимизация скорости загрузки</strong> сайта по рекомендациям Lighthouse."
- id: "subsection-design"
  active: true
  button:
    phone:
      en: "Dev."
      ru: "Два"
    base:
      en: "Design"
      ru: "Дизайн"
  content:
    en:
      - "<strong>Websites and promotional materials</strong> in academic traditions of visual arts."
      - "<strong>UX Design</strong>: Proprietary heuristics based on Gestalt principles and other psychological approaches. Complete production cycle — from requirement gathering and customer development (CustDev) to hallway testing as part of iterative improvements."
      - "<strong>UI and Communication Design</strong>: Key visuals, prototypes, and hi-fi design mockups. Expert in Material Design and Apple&rsquo;s Human Interface Guidelines (HIG)."
      - "<strong>Design Systems</strong>, Illustrations, Animation."
    ru:
      - "<strong>Веб-сайты и промоматериалы</strong> в академических традициях визуальных искусств."
      - "<strong>UX</strong>: авторские эвристики на основе гештальт-подходов и др. направлений в психологии; полный производственный цикл — от сбора требований и CustDev до коридорных тестов в рамках итеративных улучшений."
      - "<strong>UI и коммуникационный дизайн</strong>: key visuals, прототипы, hi-fi дизайн-макеты. Material Design и HIG — в совершенстве."
      - "<strong>Дизайн-системы</strong>, иллюстрации, анимация."

- id: "subsection-marketing"
  active: false
  button:
    phone:
      en: "Mark."
      ru: "Три"
    base:
      en: "Marketing"
      ru: "Маркетинг"
  content:
    en:
      - "<strong>Setting up campaigns</strong> in Google Ads."
      - "<strong>SEO and ASO</strong>: on-page optimization."
      - "<strong>Analytics</strong>, growth hacking, CRO."
      - "<strong>Email marketing</strong>: launch transactional, promotional and newsletter campaigns in MailChimp."
    ru:
      - "<strong>Настройка кампаний</strong> в Google Ads и Директе, «медийка»."
      - "<strong>SEО и ASO</strong>: техническая оптимизация и наращивание ссылочной массы."
      - "<strong>Контент-маркетинг</strong>, блоггинг. В том числе — мультимедийные лонгриды."
      - "<strong>Аналитика</strong>, гроус-хакинг, CRO."
      - "<strong>Email-маркетинг</strong>: запуск кампаний в MailChimp и альтернативах. Трансакционные, триггерные, акционные и новостные рассылки."
      - "<strong>SMM</strong>: создание и поддержка корпоративных аккаунтов, наращивание и вовлечение подписчиков."
